### ISSUE TITLE
intermittent exception in updates metrics database (?)

### ISSUE THREAD

**Issue by ehenneken** [adsabs/adsdata#58]
For some, as yet, unknown reason some records sometimes throw an exception when the metrics database is updated. This happened on July 8th (log file: `build_docs.py.20150708-043543`), for example for record `2000MaMol..33.9471F`. The entire traceback is as follows:
  `2015-07-08 12:05:01,763 ERROR Traceback (most recent call last):
  File "/proj/adsx/beer/adsdata/scripts/build_docs.py", line 81, in run
    self.psql['session'].save_metrics_records(self.psql['payload'])
  File "/proj/adsx/beer/adsdata/adsdata/psql_session.py", line 59, in save_metrics_records
    current = self.session.query(Metrics).filter(Metrics.bibcode==record['bibcode']).one()
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2395, in one
    ret = list(self)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2438, in __iter__
    return self._execute_and_instances(context)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/orm/query.py", line 2453, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "/proj/adsx/beer/python/lib/python2.6/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
DatabaseError: (DatabaseError) server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
 'SELECT metrics.id AS metrics_id, metrics.bibcode AS metrics_bibcode, metrics.refereed AS metrics_refereed, metrics.rn_citations AS metrics_rn_citations, metrics.rn_citation_data AS metrics_rn_citation_data, metrics.rn_citations_hist AS metrics_rn_citations_hist, metrics.downloads AS metrics_downloads, metrics.reads AS metrics_reads, metrics.an_citations AS metrics_an_citations, metrics.refereed_citation_num AS metrics_refereed_citation_num, metrics.citation_num AS metrics_citation_num, metrics.reference_num AS metrics_reference_num, metrics.citations AS metrics_citations, metrics.refereed_citations AS metrics_refereed_citations, metrics.author_num AS metrics_author_num, metrics.an_refereed_citations AS metrics_an_refereed_citations, metrics.modtime AS metrics_modtime \nFROM metrics \nWHERE metrics.bibcode = %(bibcode_1)s' {'bibcode_1': '2000MaMol..33.9471F'}`

**Comment by ehenneken** [comment]
The previous time this happened, it was caused by the fact that some records did not comply with the updated ORM. This is not the case with `2000MaMol..33.9471F`; the record in the metrics database contains all columns required by the ORM.

**Comment by ehenneken** [comment]
To get a feel for the size this problem, I did the following on the 2015 adsdata logs for "build_docs":

  `grep bibcode_1 build_docs.py.2015* | grep -v immutabledict | perl -pi -e 's/^build_docs\.py\.(\d{6}).*/$1/g' | sort | uniq -c`

which counts the bibcodes in each month that threw the above exception. Result:

```
108276 201504
     1 201506
     3 201507
```

**Comment by ehenneken** [comment]
As a test I updated information for `2000MaMol..33.9471F` so that adsdata would be forced to update the metrics database for this record. Result: `build_docs.py.20150716-041109` has

  `2015-07-16 11:27:05,909 INFO [metrics_data] Updated 2000MaMol..33.9471F`

i.e. no exception was thrown.
